env:
  browser: true
  es6: true
  node: true

extends:
  - airbnb-base

plugins:
  - babel

parser: babel-eslint

parserOptions:
  ecmaVersion: 11
  sourceType: module

rules:
  no-console: 0
  no-param-reassign: 0
